version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false

    ports: 
      - 51773
      - 32916:52773
      - 53773
    volumes:
      - ./:/home/irisowner/irisdev/